
packaging_format = 2

id = "gonic"
name = "Gonic"
description.en = "Music streaming server / free-software subsonic server API implementation"
description.fr = "Serveur de streaming de musique / implémentation libre de l'API Subsonic"

version = "0.22.0~ynh1"

maintainers = ["otm33GH"]

[upstream]
license = "GPL-3.0-only"
admindoc = "https://github.com/sentriz/gonic/wiki"
userdoc = "https://github.com/sentriz/gonic/wiki"
code = "https://github.com/sentriz/gonic"


[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = ["amd64","arm64"]
multi_instance = false

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]

    [resources.sources.main]

    amd64.url = "https://github.com/sentriz/gonic/releases/download/v0.22.0/gonic-linux-amd64-v0.22.0"    
    amd64.sha256 = "2426c1e573a21c7a165e3ebb7242a2aebcd29cab402db4cf18a78a29e3d4e089"
    arm64.url = "https://github.com/sentriz/gonic/releases/download/v0.22.0/gonic-linux-arm64-v0.22.0"    
    arm64.sha256 = "d5f92662fd06bfdee024d0965f19fe8d8724f7a2ec705554053ef817327a84e3"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "gonic-linux-amd64-.*"
    autoupdate.asset.arm64 = "gonic-linux-arm64-.*"

    rename = "gonic"

    [resources.system_user]

    [resources.install_dir]


    [resources.data_dir]
    subdirs = ["music", "podcast", "playlists", "database"]

    [resources.permissions]

    main.url = "/"

    [resources.ports]

    [resources.apt]

    packages = "ffmpeg mpv"