
packaging_format = 2

id = "gonic"
name = "Gonic"
description.en = "Music streaming server / free-software subsonic server API implementation"
description.fr = "Serveur de streaming de musique / implémentation libre de l'API Subsonic"

version = "0.21.0~ynh1"

maintainers = ["otm33GH"]

[upstream]
license = "GPL-3.0-only"
admindoc = "https://github.com/sentriz/gonic/wiki"
userdoc = "https://github.com/sentriz/gonic/wiki"
code = "https://github.com/sentriz/gonic"


[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = ["amd64","arm64"]
multi_instance = false

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]

    [resources.sources.main]

    amd64.url = "https://github.com/sentriz/gonic/releases/download/v0.21.0/gonic-linux-amd64-v0.21.0"    
    amd64.sha256 = "08fdc1c23d6ba816bf6932a646a2822d25bcaad666a58bf2bbc8643afd350fcc"
    arm64.url = "https://github.com/sentriz/gonic/releases/download/v0.21.0/gonic-linux-arm64-v0.21.0"    
    arm64.sha256 = "762a8209d6303fff55159d5ef1df63d3d51525a7f13613390653416fd7977e42"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "gonic-linux-amd64-.*"
    autoupdate.asset.arm64 = "gonic-linux-arm64-.*"

    rename = "gonic"

    [resources.system_user]

    [resources.install_dir]


    [resources.data_dir]
    subdirs = ["music", "podcast", "playlists", "database"]

    [resources.permissions]

    main.url = "/"

    [resources.ports]

    [resources.apt]

    packages = "ffmpeg mpv"